// <auto-generated />
namespace ProductManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedCategoryTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedCategoryTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101051235301_SeedCategoryTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
